import { Dumbbell, Sparkles } from 'lucide-react';
import { ProtectedPage } from '@/components/ProtectedPage';
import { PageHeader } from '@/components/PageHeader';
import { CrudResource } from '@/components/CrudResource';
import { WorkoutExercisePanel } from '@/components/WorkoutExercisePanel';
import { requireSession } from '@/lib/auth';
import { createClient } from '@/lib/supabase/server';

export default async function TreinosPage(){
  const {profile}=await requireSession(); const supabase=await createClient(); let mq=supabase.from('members').select('id,full_name').order('full_name');let tq=supabase.from('profiles').select('id,display_name').eq('role','trainer').order('display_name');let wq=supabase.from('workouts').select('id,name,members(full_name)').order('created_at',{ascending:false});if(profile.organization_id){mq=mq.eq('organization_id',profile.organization_id);tq=tq.eq('organization_id',profile.organization_id);wq=wq.eq('organization_id',profile.organization_id)}const [{data:members},{data:trainers},{data:workoutList}]=await Promise.all([mq,tq,wq]);
  return <ProtectedPage><div className="page"><PageHeader title="Treinos" description="Planejamento de treinos por aluno, objetivo, validade e aprovação profissional." actions={<span className="badge badge-green"><Sparkles size={13}/> IA assistiva com aprovação humana</span>}/><div className="card hero" style={{marginBottom:18}}><div><h2>Treinador no controle. IA como assistente.</h2><p>O GYMFIT foi estruturado para receber um gerador de sugestões de treino, mas toda ficha sugerida deve ser revisada e aprovada pelo profissional antes da publicação ao aluno.</p></div><div className="ai-box"><div className="ai-title"><Dumbbell size={18}/> Estrutura avançada</div><div className="ai-list"><div className="ai-item">Séries, repetições, carga, descanso, cadência, RPE, RIR e método.</div><div className="ai-item">Histórico de execução e progressão de carga por exercício.</div><div className="ai-item">Vídeos, instruções e feedback do aluno.</div></div></div></div><CrudResource readOnly={profile.role==='student'} table="workouts" organizationId={profile.organization_id} select="*,members(full_name),profiles!workouts_trainer_id_fkey(display_name)" searchFields={['name','objective','members.full_name','profiles.display_name']} addLabel="Novo treino" emptyText="Nenhum treino cadastrado." columns={[{key:'name',label:'Treino'},{key:'members.full_name',label:'Aluno'},{key:'profiles.display_name',label:'Treinador'},{key:'objective',label:'Objetivo'},{key:'expires_on',label:'Validade',format:'date'},{key:'status',label:'Status',format:'status'}]} fields={[{name:'name',label:'Nome do treino',required:true},{name:'member_id',label:'Aluno',type:'select',required:true,options:(members||[]).map(m=>({label:m.full_name,value:m.id}))},{name:'trainer_id',label:'Treinador',type:'select',options:(trainers||[]).map(t=>({label:t.display_name,value:t.id}))},{name:'objective',label:'Objetivo'},{name:'starts_on',label:'Início',type:'date',defaultValue:new Date().toISOString().slice(0,10)},{name:'expires_on',label:'Validade',type:'date'},{name:'status',label:'Status',type:'select',defaultValue:'active',required:true,options:[{label:'Ativo',value:'active'},{label:'Inativo',value:'inactive'},{label:'Pendente',value:'pending'}]},{name:'notes',label:'Observações',type:'textarea'}]}/><section style={{marginTop:28}}><div className="section-head"><h2>Exercícios das fichas</h2><span>Séries · carga · métodos · RPE/RIR</span></div><WorkoutExercisePanel readOnly={profile.role==='student'} workouts={(workoutList||[]).map((w:any)=>({id:w.id,name:w.name,memberName:w.members?.full_name||'Aluno'}))}/></section></div></ProtectedPage>;
}
