import { AlertTriangle, Bot, Sparkles, UserCheck } from 'lucide-react';
import { ProtectedPage } from '@/components/ProtectedPage';
import { PageHeader } from '@/components/PageHeader';
import { CrudResource } from '@/components/CrudResource';
import { StatCard } from '@/components/StatCard';
import { requireSession } from '@/lib/auth';
import { createClient } from '@/lib/supabase/server';

export default async function RetencaoPage(){const {profile}=await requireSession();const supabase=await createClient();let mq=supabase.from('members').select('id,full_name').order('full_name');let rq=supabase.from('churn_scores').select('score,risk_level');if(profile.organization_id){mq=mq.eq('organization_id',profile.organization_id);rq=rq.eq('organization_id',profile.organization_id)}const [{data:members},{data:risks}]=await Promise.all([mq,rq]);const high=(risks||[]).filter(r=>r.score>=70).length,medium=(risks||[]).filter(r=>r.score>=40&&r.score<70).length,avg=(risks||[]).length?Math.round((risks||[]).reduce((a,r)=>a+Number(r.score),0)/(risks||[]).length):0;return <ProtectedPage><div className="page"><PageHeader title="Retenção inteligente" description="Risco de evasão explicável, fatores, ações sugeridas e acompanhamento da recuperação." actions={<span className="badge badge-green"><Bot size={13}/> GYMFIT Intelligence</span>}/><div className="grid grid-3" style={{marginBottom:18}}><StatCard label="Alto risco" value={String(high)} foot="Pontuação igual ou superior a 70" icon={AlertTriangle} tone="negative"/><StatCard label="Risco moderado" value={String(medium)} foot="Pontuação entre 40 e 69" icon={Sparkles} tone="neutral"/><StatCard label="Risco médio da base" value={`${avg}%`} foot="Média dos scores calculados" icon={UserCheck}/></div><div className="card hero" style={{marginBottom:18}}><div><h2>Não mostre apenas um número. Explique o porquê.</h2><p>O motor foi modelado para guardar fatores e ações recomendadas. A automação de cálculo pode ser ligada depois a uma função agendada ou serviço de IA.</p></div><div className="ai-box"><div className="ai-title"><Sparkles size={18}/> Exemplo de explicação</div><div className="ai-list"><div className="ai-item">Frequência caiu 68% nos últimos 30 dias.</div><div className="ai-item">Nenhum contato do treinador há 22 dias.</div><div className="ai-item">Plano vence em 14 dias → criar tarefa de recuperação.</div></div></div></div><CrudResource table="churn_scores" organizationId={profile.organization_id} select="*,members(full_name)" orderBy="calculated_at" searchFields={['members.full_name','risk_level']} addLabel="Registrar análise" emptyText="Nenhum score de retenção calculado." columns={[{key:'members.full_name',label:'Aluno'},{key:'score',label:'Risco %'},{key:'risk_level',label:'Nível'},{key:'calculated_at',label:'Calculado em',format:'datetime'}]} fields={[{name:'member_id',label:'Aluno',type:'select',required:true,options:(members||[]).map(m=>({label:m.full_name,value:m.id}))},{name:'score',label:'Score de risco (0-100)',type:'number',required:true},{name:'risk_level',label:'Nível',type:'select',required:true,options:[{label:'Baixo',value:'low'},{label:'Moderado',value:'medium'},{label:'Alto',value:'high'},{label:'Crítico',value:'critical'}]}]}/></div></ProtectedPage>}
