import { BarChart3, CreditCard, Target, TrendingUp, Users } from 'lucide-react';
import { ProtectedPage } from '@/components/ProtectedPage';
import { PageHeader } from '@/components/PageHeader';
import { StatCard } from '@/components/StatCard';
import { requireSession } from '@/lib/auth';
import { createClient } from '@/lib/supabase/server';

function money(n:number){return new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(n)}
export default async function RelatoriosPage(){const {profile}=await requireSession();const supabase=await createClient();let q=supabase.from('organization_kpis').select('*');if(profile.organization_id)q=q.eq('organization_id',profile.organization_id);const {data}=await q;const k=(data||[]).reduce((a:any,r:any)=>({active_members:a.active_members+Number(r.active_members||0),new_members_month:a.new_members_month+Number(r.new_members_month||0),income_month:a.income_month+Number(r.income_month||0),expense_month:a.expense_month+Number(r.expense_month||0),overdue_count:a.overdue_count+Number(r.overdue_count||0),leads_month:a.leads_month+Number(r.leads_month||0)}),{active_members:0,new_members_month:0,income_month:0,expense_month:0,overdue_count:0,leads_month:0});const max=Math.max(k.income_month,k.expense_month,1);return <ProtectedPage><div className="page"><PageHeader title="BI & Relatórios" description="Indicadores executivos com leitura simples para transformar dados em decisão."/><div className="grid grid-4"><StatCard label="Alunos ativos" value={String(k.active_members)} foot={`+${k.new_members_month} no mês`} icon={Users}/><StatCard label="Receita" value={money(k.income_month)} foot="Receita paga no mês" icon={TrendingUp}/><StatCard label="Despesas" value={money(k.expense_month)} foot="Despesas pagas no mês" icon={CreditCard} tone="negative"/><StatCard label="Leads" value={String(k.leads_month)} foot="Entradas no funil no mês" icon={Target}/></div><div className="grid grid-2" style={{marginTop:18}}><section className="card card-pad"><div className="section-head"><h2>Receita x Despesa</h2><span>Mês atual</span></div><div className="metric-line"><span>Receita</span><strong>{money(k.income_month)}</strong></div><div className="progress"><span style={{width:`${k.income_month/max*100}%`}}/></div><div className="metric-line"><span>Despesa</span><strong>{money(k.expense_month)}</strong></div><div className="progress"><span style={{width:`${k.expense_month/max*100}%`}}/></div><div className="metric-line"><span>Resultado</span><strong className={k.income_month-k.expense_month>=0?'positive':'negative'}>{money(k.income_month-k.expense_month)}</strong></div></section><section className="card card-pad"><div className="section-head"><h2>Centro de decisões</h2><span>GYMFIT BI</span></div><div className="ai-list"><div className="ai-item"><BarChart3 size={15}/> Compare desempenho entre unidades e períodos.</div><div className="ai-item">Acompanhe conversão de leads, ticket médio e renovação.</div><div className="ai-item">Cruze frequência, evolução e risco de evasão.</div><div className="ai-item">Exporte dados e conecte ferramentas externas por API.</div></div></section></div></div></ProtectedPage>}
