'use client';
import { useCallback,useEffect,useMemo,useState } from 'react';
import { Plus,Search,Shield,UserPlus,X } from 'lucide-react';
import { createClient } from '@/lib/supabase/client';
import { StatusBadge } from '@/components/StatusBadge';
import type { AppRole } from '@/lib/types';

const roleNames:Record<string,string>={platform_admin:'ADM da plataforma',master:'Master',manager:'Gerente',trainer:'Treinador',student:'Aluno'};
export function UserAccessManager({actorRole,organizationId,members,organizations=[]}:{actorRole:AppRole;organizationId:string|null;members:{id:string;full_name:string;user_id:string|null}[];organizations?:{id:string;name:string}[]}){
 const supabase=useMemo(()=>createClient(),[]);const [rows,setRows]=useState<any[]>([]),[loading,setLoading]=useState(true),[search,setSearch]=useState(''),[modal,setModal]=useState(false),[error,setError]=useState(''),[toast,setToast]=useState(''),[saving,setSaving]=useState(false),[form,setForm]=useState<any>({role:actorRole==='manager'?'trainer':'manager'});
 const load=useCallback(async()=>{setLoading(true);let q=supabase.from('profiles').select('id,username,display_name,role,status,organization_id,organizations(name)').order('created_at',{ascending:false});if(organizationId)q=q.eq('organization_id',organizationId);const {data,error}=await q;if(error)setError(error.message);else setRows(data||[]);setLoading(false)},[supabase,organizationId]);useEffect(()=>{void load()},[load]);useEffect(()=>{if(toast){const t=setTimeout(()=>setToast(''),2600);return()=>clearTimeout(t)}},[toast]);
 const allowed=actorRole==='platform_admin'?['master','manager','trainer','student']:actorRole==='master'?['manager','trainer','student']:['trainer','student']; const filtered=rows.filter(r=>`${r.display_name} ${r.username} ${r.role}`.toLowerCase().includes(search.toLowerCase()));
 function set(k:string,v:any){setForm((f:any)=>({...f,[k]:v}))}
 async function submit(e:React.FormEvent){e.preventDefault();setSaving(true);setError('');try{const res=await fetch('/api/users',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({...form,organization_id:form.organization_id||organizationId})});const json=await res.json();if(!res.ok)throw new Error(json.error||'Erro ao criar acesso.');setModal(false);setForm({role:allowed[0]});setToast('Acesso criado com sucesso.');await load()}catch(err){setError(err instanceof Error?err.message:'Erro inesperado.')}finally{setSaving(false)}}
 return <><div className="toolbar"><label className="search-box" style={{width:300}}><Search size={16}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Buscar usuário..."/></label><button className="btn btn-primary" onClick={()=>{setError('');setModal(true)}}><Plus size={16}/>Novo acesso</button></div>{error&&!modal&&<div className="error-box">{error}</div>}<div className="card table-wrap">{loading?<div className="empty">Carregando...</div>:filtered.length===0?<div className="empty"><Shield/><div>Nenhum usuário encontrado.</div></div>:<table><thead><tr><th>Nome</th><th>Usuário</th><th>Perfil</th><th>Academia</th><th>Status</th></tr></thead><tbody>{filtered.map(r=><tr key={r.id}><td><strong>{r.display_name}</strong></td><td>{r.username}</td><td>{roleNames[r.role]||r.role}</td><td>{r.organizations?.name||'Plataforma'}</td><td><StatusBadge status={r.status}/></td></tr>)}</tbody></table>}</div>
 {modal&&<div className="modal-backdrop"><form className="modal" onSubmit={submit}><div className="modal-head"><h3>Criar acesso</h3><button className="icon-btn" type="button" onClick={()=>setModal(false)}><X size={17}/></button></div><div className="modal-body">{error&&<div className="error-box">{error}</div>}<div className="form-grid"><div className="form-field"><label>Nome completo</label><input className="input" required value={form.display_name||''} onChange={e=>set('display_name',e.target.value)}/></div><div className="form-field"><label>Usuário</label><input className="input" required value={form.username||''} onChange={e=>set('username',e.target.value)}/></div><div className="form-field"><label>Perfil</label><select className="select" required value={form.role||allowed[0]} onChange={e=>set('role',e.target.value)}>{allowed.map(r=><option value={r} key={r}>{roleNames[r]}</option>)}</select></div>{actorRole==='platform_admin'&&<div className="form-field"><label>Academia</label><select className="select" value={form.organization_id||''} onChange={e=>set('organization_id',e.target.value)}><option value="">Selecione</option>{organizations.map(o=><option key={o.id} value={o.id}>{o.name}</option>)}</select></div>}{form.role==='student'&&<div className="form-field full"><label>Vincular ao cadastro de aluno</label><select className="select" value={form.member_id||''} onChange={e=>set('member_id',e.target.value)}><option value="">Selecione o aluno</option>{members.filter(m=>!m.user_id).map(m=><option key={m.id} value={m.id}>{m.full_name}</option>)}</select></div>}<div className="form-field full"><label>Senha inicial</label><input className="input" type="password" minLength={8} required value={form.password||''} onChange={e=>set('password',e.target.value)}/></div></div></div><div className="modal-footer"><button type="button" className="btn" onClick={()=>setModal(false)}>Cancelar</button><button className="btn btn-primary" disabled={saving}>{saving?'Criando...':<><UserPlus size={16}/> Criar acesso</>}</button></div></form></div>}{toast&&<div className="toast">{toast}</div>}</>;
}
