'use client';
import { useState } from 'react';
import { Dumbbell } from 'lucide-react';
import { CrudResource } from '@/components/CrudResource';

export function WorkoutExercisePanel({workouts,readOnly}:{workouts:{id:string;name:string;memberName:string}[];readOnly:boolean}){
 const [workoutId,setWorkoutId]=useState(workouts[0]?.id||'');
 if(!workouts.length)return <div className="card empty"><Dumbbell/><div>Crie um treino antes de adicionar exercícios.</div></div>;
 return <><div className="toolbar"><div className="form-field" style={{minWidth:320}}><label>Ficha de treino</label><select className="select" value={workoutId} onChange={e=>setWorkoutId(e.target.value)}>{workouts.map(w=><option value={w.id} key={w.id}>{w.name} · {w.memberName}</option>)}</select></div></div><CrudResource key={workoutId} readOnly={readOnly} table="workout_exercises" filter={{workout_id:workoutId}} fixedValues={{workout_id:workoutId}} orderBy="order_index" orderAscending={true} searchFields={['exercise_name','muscle_group','method']} addLabel="Adicionar exercício" emptyText="Nenhum exercício nesta ficha." columns={[{key:'order_index',label:'#'},{key:'exercise_name',label:'Exercício'},{key:'muscle_group',label:'Grupo'},{key:'sets',label:'Séries'},{key:'reps',label:'Repetições'},{key:'load_kg',label:'Carga kg'},{key:'rest_seconds',label:'Descanso s'},{key:'method',label:'Método'}]} fields={[{name:'order_index',label:'Ordem',type:'number',defaultValue:1},{name:'exercise_name',label:'Exercício',required:true},{name:'muscle_group',label:'Grupo muscular'},{name:'sets',label:'Séries',type:'number'},{name:'reps',label:'Repetições',placeholder:'8-12, AMRAP...'},{name:'load_kg',label:'Carga (kg)',type:'number',step:'0.01'},{name:'rest_seconds',label:'Descanso (segundos)',type:'number'},{name:'cadence',label:'Cadência',placeholder:'3-1-1-0'},{name:'method',label:'Método',type:'select',options:[{label:'Tradicional',value:'traditional'},{label:'Bi-set',value:'bi-set'},{label:'Tri-set',value:'tri-set'},{label:'Drop-set',value:'drop-set'},{label:'Rest-pause',value:'rest-pause'},{label:'Pirâmide',value:'pyramid'},{label:'Circuito',value:'circuit'},{label:'AMRAP',value:'amrap'},{label:'EMOM',value:'emom'}]},{name:'rpe_target',label:'RPE alvo',type:'number',step:'0.1'},{name:'rir_target',label:'RIR alvo',type:'number'},{name:'video_url',label:'URL do vídeo'},{name:'instructions',label:'Instruções técnicas',type:'textarea'}]}/></>;
}
