import { CreditCard, WalletCards } from 'lucide-react';
import { ProtectedPage } from '@/components/ProtectedPage';
import { PageHeader } from '@/components/PageHeader';
import { CrudResource } from '@/components/CrudResource';
import { StatCard } from '@/components/StatCard';
import { requireSession } from '@/lib/auth';
import { createClient } from '@/lib/supabase/server';

export default async function FinanceiroPage(){
  const {profile}=await requireSession(); const supabase=await createClient(); const org=profile.organization_id;
  let mq=supabase.from('members').select('id,full_name').order('full_name'); let cq=supabase.from('financial_categories').select('id,name,type').order('name'); let tq=supabase.from('transactions').select('amount,type,payment_status'); if(org){mq=mq.eq('organization_id',org);cq=cq.eq('organization_id',org);tq=tq.eq('organization_id',org)}
  const [{data:members},{data:cats},{data:txs}]=await Promise.all([mq,cq,tq]);
  const income=(txs||[]).filter(t=>t.type==='income'&&t.payment_status==='paid').reduce((a,t)=>a+Number(t.amount),0); const expense=(txs||[]).filter(t=>t.type==='expense'&&t.payment_status==='paid').reduce((a,t)=>a+Number(t.amount),0); const overdue=(txs||[]).filter(t=>t.payment_status==='overdue').reduce((a,t)=>a+Number(t.amount),0); const money=(n:number)=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(n);
  return <ProtectedPage><div className="page"><PageHeader title="Financeiro" description="Receitas, despesas, cobranças, inadimplência e meios de pagamento em uma visão integrada."/><div className="grid grid-3" style={{marginBottom:18}}><StatCard label="Receitas pagas" value={money(income)} foot="Total carregado na base" icon={WalletCards}/><StatCard label="Despesas pagas" value={money(expense)} foot="Custos confirmados" icon={CreditCard} tone="negative"/><StatCard label="Em atraso" value={money(overdue)} foot="Cobranças vencidas" icon={CreditCard} tone="negative"/></div><CrudResource readOnly={profile.role==='student'} table="transactions" organizationId={org} select="*,members(full_name),financial_categories(name)" searchFields={['description','members.full_name','payment_method']} addLabel="Novo lançamento" emptyText="Nenhum lançamento financeiro." columns={[{key:'description',label:'Descrição'},{key:'members.full_name',label:'Aluno'},{key:'type',label:'Tipo'},{key:'amount',label:'Valor',format:'money'},{key:'due_date',label:'Vencimento',format:'date'},{key:'payment_status',label:'Status',format:'status'}]} fields={[{name:'description',label:'Descrição',required:true},{name:'type',label:'Tipo',type:'select',required:true,defaultValue:'income',options:[{label:'Receita',value:'income'},{label:'Despesa',value:'expense'}]},{name:'amount',label:'Valor',type:'number',step:'0.01',required:true},{name:'member_id',label:'Aluno',type:'select',options:(members||[]).map(m=>({label:m.full_name,value:m.id}))},{name:'category_id',label:'Categoria',type:'select',options:(cats||[]).map(c=>({label:`${c.name} · ${c.type==='income'?'Receita':'Despesa'}`,value:c.id}))},{name:'due_date',label:'Vencimento',type:'date'},{name:'payment_status',label:'Situação',type:'select',required:true,defaultValue:'pending',options:[{label:'Pendente',value:'pending'},{label:'Pago',value:'paid'},{label:'Atrasado',value:'overdue'},{label:'Cancelado',value:'cancelled'},{label:'Estornado',value:'refunded'}]},{name:'paid_at',label:'Data do pagamento',type:'datetime-local'},{name:'payment_method',label:'Meio de pagamento',type:'select',options:[{label:'Pix',value:'pix'},{label:'Pix Automático',value:'pix_automatico'},{label:'Cartão',value:'card'},{label:'Boleto',value:'boleto'},{label:'Dinheiro',value:'cash'}]},{name:'notes',label:'Observações',type:'textarea'}]}/></div></ProtectedPage>;
}
